"""
models/alert.py
===============
Alert records generated by the Alert Engine.
Every alert must include a human-readable description (why did it fire),
an impact statement (what does this affect), and a recommended action.
"""

import enum
from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class AlertSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class FaultType(str, enum.Enum):
    DRIFT = "DRIFT"
    BIAS = "BIAS"
    NOISE = "NOISE"
    STUCK = "STUCK"
    MISSING = "MISSING"
    INTERMITTENT = "INTERMITTENT"
    SPIKE = "SPIKE"
    SAMPLING_FAILURE = "SAMPLING_FAILURE"        # Phase 3: ADC/packet-loss dropout
    CROSS_SENSOR_INCONSISTENCY = "CROSS_SENSOR_INCONSISTENCY"
    LOW_RELIABILITY = "LOW_RELIABILITY"
    LOW_PREDICTION_TRUST = "LOW_PREDICTION_TRUST"
    UNKNOWN = "UNKNOWN"


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    sensor_id: Mapped[str] = mapped_column(
        String(50), ForeignKey("sensors.id", ondelete="CASCADE"), nullable=True
    )  # nullable: some alerts are machine-level, not sensor-level
    machine_id: Mapped[str] = mapped_column(String(50), nullable=True)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity), nullable=False
    )
    fault_type: Mapped[FaultType] = mapped_column(
        Enum(FaultType), nullable=False
    )
    status: Mapped[AlertStatus] = mapped_column(
        Enum(AlertStatus), default=AlertStatus.ACTIVE, nullable=False
    )

    # What happened — the core explainability field
    description: Mapped[str] = mapped_column(Text, nullable=False)
    # What will be affected downstream
    impact: Mapped[str] = mapped_column(Text, nullable=True)
    # What to do about it
    recommended_action: Mapped[str] = mapped_column(Text, nullable=True)

    # Supporting metrics at time of alert
    health_score_at_alert: Mapped[float] = mapped_column(Float, nullable=True)
    trust_score_at_alert: Mapped[float] = mapped_column(Float, nullable=True)

    resolved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships
    sensor: Mapped["Sensor"] = relationship("Sensor", back_populates="alerts")  # noqa: F821

    __table_args__ = (
        Index("ix_alerts_sensor_ts", "sensor_id", "timestamp"),
        Index("ix_alerts_machine_ts", "machine_id", "timestamp"),
        Index("ix_alerts_status", "status"),
    )

    def __repr__(self) -> str:
        return (
            f"<Alert id={self.id} sensor={self.sensor_id} "
            f"severity={self.severity} fault={self.fault_type} status={self.status}>"
        )
